name: Publish

on:
  push:
    branches: ["master"]
    paths: ["src/**"]

jobs:
  build:
    env:
      BUILD_CONFIG: "Release"
      PROJECT: "./src/MonoGame.Extensions.Hosting/MonoGame.Extensions.Hosting.csproj"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore $PROJECT

      - name: Build
        run: dotnet build $PROJECT --nologo --configuration $BUILD_CONFIG --no-restore

      - name: Publish NuGet package
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: $PROJECT
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
